version: "3.8"
services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql_db_docker
    networks:
      - myNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_admin_mysql
    networks:
      - myNetwork
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8181:80"
    depends_on:
      - mysql

  springboot:
    build: .
    container_name: store
    networks:
      - myNetwork
    environment:
      PORT: 9090
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: shop

    ports:
      - "9090:9090"
    depends_on:
      - mysql
volumes:
    mysql_data:
networks:
  myNetwork: